// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web platformu için DefaultFirebaseOptions yapılandırılmamış.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS platformu için DefaultFirebaseOptions yapılandırılmamış.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS platformu için DefaultFirebaseOptions yapılandırılmamış.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows platformu için DefaultFirebaseOptions yapılandırılmamış.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux platformu için DefaultFirebaseOptions yapılandırılmamış.',
        );
      default:
        throw UnsupportedError(
          'Bu platform için DefaultFirebaseOptions yapılandırılmamış.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb9Sia4ggEmAoY5BEBUHDo8hFdWn7Pa_g',
    appId: '1:642891441591:android:ca114581bc44ec6ac9f432',
    messagingSenderId: '642891441591',
    projectId: 'mf-master-online',
    storageBucket: 'mf-master-online.firebasestorage.app',
    androidClientId: '642891441591-8ketn88foghou9e8cf2f7lea1ss8t786.apps.googleusercontent.com',
  );
}
